### PR TITLE
fixed auth get_players, upgraded from v2 to v3

### PR DESCRIPTION
**Pull request by Danampasis**
Ubisoft upgraded to v3 of their api for profiles and users.

### CODE REVIEW

**Comment by RAYs3T** [comment]
You've duplicate the file `auth.py` into the project root - Guess that change should not be in there ... :)

**Comment by Danampasis** [comment]
True! I've deleted the duplicate one. Of course my first pr would have something wrong 😄

**Comment by Jackywathy** [comment]
Looks good, I think only @billy-yoyo can merge. Seems like only get_players works, the rest of the library needs to be adapted to v3.

**Comment by billy-yoyo** [comment]
Going to close this MR since the changes are included in @Jackywathy MR, which we'll merge instead. Thanks for the contributions everyone, and sorry for my absence.

**Pull request closed without merging**
