### PR TITLE
Updated for operators of Shifting Tides and Void Edge

### PR DESCRIPTION
**Pull request by dasBunny**
I added the statistic names for the new operators and changed the Operator URL to the current one.

### CODE REVIEW

**Comment by billy-yoyo** [comment]
Looks good to me, thanks :)

**Comment by billy-yoyo** [comment]
released in v1.3.0

**Comment by scainimatteo** [comment]
where did you get the hash code? i can't find it :(
i would like to know it to update the library

**Comment by billy-yoyo** [comment]
@scainimatteo this old ticket https://github.com/billy-yoyo/RainbowSixSiege-Python-API/issues/14 has a bit more info on how to get the hash. I'm at work right now so can't do it myself

**Pull request merged**
